name: ozone_poptart
description: Generated Dart types and method descriptors for Ozone lexicons.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  characters: ^1.4.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  bluesky_poptart:
    path: ../bluesky
  poptart_lex:
    path: ../../../poptart/packages/poptart_lex
  poptart_core:
    path: ../../../poptart/packages/poptart_core
  poptart_primitives:
    path: ../../../poptart/packages/poptart_primitives
  poptart_xrpc:
    path: ../../../poptart/packages/poptart_xrpc

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.26.2

dependency_overrides:
  bluesky_poptart:
    path: ../bluesky
  poptart_lex:
    path: ../../../poptart/packages/poptart_lex
  poptart_core:
    path: ../../../poptart/packages/poptart_core
  poptart_primitives:
    path: ../../../poptart/packages/poptart_primitives
  poptart_xrpc:
    path: ../../../poptart/packages/poptart_xrpc
