name: standard_poptart
description: Generated Dart types and method descriptors for Standard.site lexicons.
version: 0.1.1
homepage: https://poptart.xyz
documentation: https://poptart.xyz
repository: https://github.com/sprksocial/poptart_lexicons
issue_tracker: https://github.com/sprksocial/poptart_lexicons/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  characters: ^1.4.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  poptart_core: ^0.1.0
  poptart_lex: ^0.1.0
  poptart_primitives: ^0.1.0
  poptart_xrpc: ^0.1.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.26.2
